VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ILayout"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
''' - - - - - - - - - - - - - - - - - - - - -
''' <summary>   </summary>
''' - - - - - - - - - - - - - - - - - - - - -
Option Explicit

Public Sub BindControlLayout(ByVal a_parent As Object, ByVal a_child As MSForms.Control, ByVal a_anchorEdges As AnchorEdges)
End Sub

Public Sub ResizeLayout()
End Sub
