VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IThingComparisonViewFactory"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "ThingComparer"
Option Explicit

Public Function Create(ByVal Context As cc_isr_MVVM.IAppContext, ByVal ViewModel As ThingComparisonViewModel) As IView
End Function
